### ISSUE TITLE
Ready-made docker-compose file

### ISSUE THREAD

**Issue by dodekaphilist** [Yetangitu/Spodcast#15]
Since I already spent a couple of hours trying to get this running without success, I was wondering if it would be possible to provide a simple docker-compose file, that one could plug into Portainer and Spodcast would just work on a provided port. I imagine something like this:

```
version: '3'
services:
  spodcast:
    image: heywoodlh/spodcast 
    restart: always
    ports:
      - 80:80
    volumes:
      - ./spodcast:/data
    environment:
      SPOTIFY_USERNAME: "username"
      SPOTIFY_PASSWORD: "password"
```

By using environment variables, the initial setup could be improved so that the user would not be obliged to handle credential files himself but rather let the program do that.
Also at least for me, the whole web-server thing is really complicated with configuration and permission managment. I think, it would tremendously help beginners if something for this would be included in the docker image of Spodcast. After all, the application is of little use without a proper RSS feed server.

Since this might be a little bit more complicated to change, for the moment I would also just be happy to get some guidance how to setup a web-server in docker with the necessary steps for configuration. Thank you! :)
